### ISSUE TITLE
Missing synset: odenet-8722-a

### ISSUE THREAD

**Issue by goodmami** [hdaSprachtechnologie/odenet#17]
When I try to validate the XML file with the WN-LMF-1.0 DTD, I get an error:

```console
$ xmlstarlet val -d WN-LMF-1.0.dtd -e odenet/wordnet/deWordNet.xml
Attempt to load network entity http://globalwordnet.github.io/schemas/WN-LMF-1.0.dtd
odenet/wordnet/deWordNet.xml:8529.0: IDREF attribute synset references an unknown ID "odenet-8722-a"
odenet/wordnet/deWordNet.xml - invalid
```

Here is the lexical entry (with a comment):

```xml
<LexicalEntry id="w1688">
        <Lemma writtenForm="blank" partOfSpeech="a"/>
        <Sense id="w1688_342-a" synset="odenet-342-a"/>
        <Sense id="w1688_5428-a" synset="odenet-5428-a"/>
        <Sense id="w1688_8722-a" synset="odenet-8722-a"/>  <!-- this one -->
        <Sense id="w1688_11293-a" synset="odenet-11293-a"/>
        <Sense id="w1688_15406-a" synset="odenet-15406-a"/>
        <Sense id="w1688_25233-a" synset="odenet-25233-a"/>
        <Sense id="w1688_28903-a" synset="odenet-28903-a"/>
</LexicalEntry>
```

**Comment by goodmami** [comment]
The simplest solution is to delete this line:

```xml
        <Sense id="w1688_8722-a" synset="odenet-8722-a"/>
```

After doing that, the XML validates against the DTD. I'm not sure if that is the best solution, though (maybe the missing synset should be in the lexicon).

**Comment by hdaSprachtechnologie** [comment]
Corrected (deleted) and added to the validation tests.

**Comment by goodmami** [comment]
It looks like the synset was in fact [removed](https://github.com/hdaSprachtechnologie/odenet/commit/509c758e0603d5f1469bc9fede0321319b0bee3a#diff-49c558a14c484563ec38ea3d236b62628a1cf2a5dddb462f602542d08ca1c9d6L580022) when one of its senses [was also removed](https://github.com/hdaSprachtechnologie/odenet/commit/509c758e0603d5f1469bc9fede0321319b0bee3a#diff-49c558a14c484563ec38ea3d236b62628a1cf2a5dddb462f602542d08ca1c9d6L14990), but it wasn't the only sense of the synset. So do we restore the synset or delete the other sense?

For reference, here's the synset:

```xml
<Synset id="odenet-8722-a" ili="i5968" partOfSpeech="a" dc:description="holding or containing nothing"/>
```

The sense that was removed was on the adjective lexical entry "leer".

**Comment by hdaSprachtechnologie** [comment]
yes, it was removed on purpose
