### ISSUE TITLE
odenet-2094-n: Falsche ILI korrigieren

### ISSUE THREAD

**Issue by rwingerter55** [hdaSprachtechnologie/odenet#23]
Synset `odenet-2094-n` hat die Lemmata “Viola, Viole, Bratsche”. 

Die folgenden Zeilen sind zu ändern:
```
<Synset id="odenet-2094-n" ili="i102113" partOfSpeech="n" dc:description="any of the numerous plants of the genus Viola">
	<SynsetRelation target='odenet-16112-n' relType='hypernym'/>
</Synset>
```

Richtig wäre:
```
<Synset id="odenet-2094-n" ili="i60865" partOfSpeech="n" dc:description="a bowed stringed instrument slightly larger than a violin, tuned a fifth lower">
</Synset>
```

Begründung: Nach den Lemmata ist hier nicht die Pflanze (Veilchen), sondern das Musikinstrument gemeint. 

Die richtige ILI dazu wäre:
ili=”i60865” ("viola")
dc:description:“a bowed stringed instrument slightly larger than a violin, tuned a fifth lower”

Vgl. dazu die Bedeutungserklärung:
Brat·sche <Bratsche, Bratschen> die Bratsche SUBST Viola Streichinstrument, das etwas größer als eine Violine und eine Quinte tiefer gestimmt ist
[PONS Großwörterbuch Deutsch als Fremdsprache](https://de.thefreedictionary.com/Bratsche), © PONS GmbH, Stuttgart, Germany 2015.

Die SynsetRelation mit Target odenet-16112-n (”Küchenkräuter, Kräuter”) ist zu entfernen. 

Im englischen WordNet EWN hat ili=”[i60865](https://en-word.net/ili/i60865)” als Oberbegriff ili=“i51019” (“bowed stringed instrument, string”).  

Das deutsche Äquivalent dazu ist "Streichinstrument" Dieser Begriff fehlt in OdeNet.

**Comment by hdaSprachtechnologie** [comment]
corrected

**Comment by rwingerter55** [comment]
Danke.

**Comment by rwingerter55** [comment]
In v1.4 we are back to the wrong ILI, designating a plant. 

```
    <Synset id="odenet-2094-n" ili="i102113" partOfSpeech="n" dc:description="any of the numerous plants of the genus Viola">
      <Definition>eine der zahlreichen Pflanzen der Gattung Viola</Definition>
      <SynsetRelation target="odenet-16112-n" relType="hypernym"/>
    </Synset>

```

Whereas the lemmas designate a musical instrument:

```
   <LexicalEntry id="w10116">
     <Lemma writtenForm="Viola" partOfSpeech="n"/>
     <Sense id="w10116_2094-n" synset="odenet-2094-n"/>
   </LexicalEntry>
   <LexicalEntry id="w10117">
     <Lemma writtenForm="Viole" partOfSpeech="n"/>
     <Sense id="w10117_2094-n" synset="odenet-2094-n"/>
   </LexicalEntry>
   <LexicalEntry id="w10118">
     <Lemma writtenForm="Bratsche" partOfSpeech="n"/>
     <Sense id="w10118_2094-n" synset="odenet-2094-n"/>
   </LexicalEntry>
```
