### ISSUE TITLE
Definition von `odenet-10489-n` “Ablenkung, Abschweifung, Abweichung”

### ISSUE THREAD

**Issue by rwingerter55** [hdaSprachtechnologie/odenet#24]
Mir ist die Definition von `odenet-10489-n` “Ablenkung, Abschweifung, Abweichung” aufgefallen. 

```
<Synset id="odenet-10489-n" ili="i37252" partOfSpeech="n" confidenceScore="1.0">
	<Definition>Abzweigung vom Kurs oder der Aufmerksamkeit</Definition>
</Synset>
```
Vgl. i37252 im englischen WordNet:

![image](https://user-images.githubusercontent.com/62653433/132962393-799844f1-93c1-4669-9b61-5c15701a9302.png)

Für meine Ohren klingt “Abzweigung vom Kurs” und “Abzweigung der Aufmerksamkeit” nicht sehr idiomatisch.

Mein Vorschlag (neue Definition):
```
<Synset id="odenet-10489-n" ili="i37252" partOfSpeech="n" confidenceScore="1.0">
	<Definition>Verlassen des eingeschlagenen Weges oder Themas</Definition>
</Synset>
```

**Comment by hdaSprachtechnologie** [comment]
ok

**Comment by rwingerter55** [comment]
Danke.
