### ISSUE TITLE
Update version string

### ISSUE THREAD

**Issue by goodmami** [hdaSprachtechnologie/odenet#25]
Good news on the release!

Unfortunately, the [automated release action](https://github.com/hdaSprachtechnologie/odenet/actions/workflows/release.yml) failed because the version tag (`v1.4`) doesn't match what's in the XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalResource SYSTEM "http://globalwordnet.github.io/schemas/WN-LMF-1.0.dtd">
<LexicalResource xmlns:dc="http://purl.org/dc/elements/1.1/" >
	<Lexicon id="odenet"
        ...
	version="1.3"    <!-- this should be 1.4 -->
```

#### Option 1: Delete the release, fix the version, and try again

If you want to delete the release and try again, first delete the release on GitHub (from [here](https://github.com/hdaSprachtechnologie/odenet/releases/tag/v1.4)) then delete the tag using Git ([source](https://github.community/t/how-to-delete-release-completely/1466)):

```console
$ git push --delete origin v1.4
```

After committing and pushing the updated version in the XML file, you can create the release again and it will (hopefully) go smoother this time.

#### Option 2: Manually perform the packaging step

I see there is one commit made since the release. If you do not want to include that commit in the released file, you can also perform the asset packaging step manually:

```console
$ git checkout v1.4  # switch to release commit
$ xmlstarlet val -d ../schemas/WN-LMF-1.0.dtd odenet/wordnet/deWordNet.xml   # validate
odenet/wordnet/deWordNet.xml - valid
$ mkdir odenet-1.4  # directory for the release package
$ cp odenet/wordnet/deWordNet.xml odenet-1.4/  # copy release files
$ cp LICENSE odenet-1.4/
$ cp README.md odenet-1.4/
$ cp citation.bib odenet-1.4/
$ tar -cf odenet-1.4.tar odenet-1.4/  # archive the release directory
$ xz -z odenet-1.4.tar  # compress the archive
$ rm -r odenet-1.4/  # clean up
$ git checkout master  # switch back to master branch
```

Then you can attach the `odenet-1.4.tar.xz` file to the release by going [here](https://github.com/hdaSprachtechnologie/odenet/releases/tag/v1.4), clicking the "Edit release" button, and uploading the file.

**Comment by goodmami** [comment]
Sorry, I forgot a step in Option 2. You'll need to change the version string before tar'ing the directory. That is:

```console
...
$ cp odenet/wordnet/deWordNet.xml odenet-1.4/  # (after this line)
$ sed -i 's/version="1.3"/version="1.4"/' odenet-1.4/deWordNet.xml  # fix version string
...
```

**Comment by hdaSprachtechnologie** [comment]
I hope that the problem is now solved. Thank you!

**Comment by fcbond** [comment]
Hi, 

Great to see a new release, and I can load the lexicon xml file nicely.

However, the release does not make a package usable directly by wn:
https://wn.readthedocs.io/en/latest/guides/lexicons.html#wn-lmf-packages

It would be nice if it could, and it should be possible following the steps Mike gave above, ...

So I am re-opening this.

**Comment by goodmami** [comment]
I see you were able to recreate the release, however the version string is still "1.3" when the asset-upload pipeline runs, resulting in an error:

![odenet-version](https://user-images.githubusercontent.com/1428419/133637492-b38f4754-263f-4026-892c-dc6248bb07e2.png)

I see that you've committed the updated version string in 2330f71b64964fba1a6001ebb703232f8e7ee5d7, so I suspect you did not delete the `v1.4` tag before recreating the release and instead reused the old tag, which pointed to an old commit. You'll need to delete it from the command line as shown [above](https://github.com/hdaSprachtechnologie/odenet/issues/25#issue-997275524), copied here:

```console
$ git push --delete origin v1.4
```

If you in fact did do this step, then perhaps something else is the matter.

By the way, if you want the README included in the package, you'll need to edit this line:

https://github.com/hdaSprachtechnologie/odenet/blob/7bd6b85266e9d621cdb0a173c3e73d4d9575b811/.github/workflows/release.yml#L14

So it says:

```yaml
      README: README.md
```

Be sure to push these changes before creating the release again. Hope that helps!

**Comment by hdaSprachtechnologie** [comment]
Tried again. Is this working now?

**Comment by goodmami** [comment]
Looks good to me:

```python
>>> import wn
>>> wn.download('https://github.com/hdaSprachtechnologie/odenet/releases/download/v1.4/odenet-1.4.tar.xz')
Download [##############################] (2441188/2441188 bytes) Complete
Added odenet:1.4 (Offenes Deutsches WordNet)
```

Thanks!

**Comment by goodmami** [comment]
I'll close this as it has been resolved.

Btw I think we can separate the validation and release actions so we will know if the release action will complete successfully before making the release. Perhaps by validating every commit or on a pre-release.
