### ISSUE TITLE
Synset <odenet-4847-v>

### ISSUE THREAD

**Issue by rwingerter55** [hdaSprachtechnologie/odenet#33]
Here is a proposed update to `odenet-4847-v`, which was last edited yesterday. 

**Current**

```
<Synset id="odenet-4847-v" ili="i24898" partOfSpeech="v" confidenceScore="1.0" dc:subject="noun.cognition">
	<Definition>eine Instanz des freien Denkens</Definition>
</Synset>
```

**Proposal**

```
<Synset id="odenet-4847-v" ili="i24898" partOfSpeech="v" confidenceScore="1.0" dc:subject="verb.cognition">
	<Definition>philosophische Überlegungen anstellen</Definition>
</Synset>
```

**Comment**

Yesterday, the ILI was changed from `i67296` to `i24898`. 	

This makes dc:subject and definition obsolete:
dc:subject="noun.cognition"
Definition="eine Instanz des freien Denkens"

ili ID 	Definition and Source 
-i67296 	“an instance of deliberate thinking” (pwn-3.0:05786372-n) 
-i24898 	“reason philosophically” (pwn-3.0:00630026-v) 

Cf. definitions in Wiktionary

https://en.wiktionary.org/wiki/philosophize#English
To ponder or reason out philosophically.

https://de.wiktionary.org/wiki/philosophieren
    [1] nach philosophischer Erkenntnis des Ganzen bzw. des Seins suchen
    [2] über etwas nachdenken

**Comment by rwingerter55** [comment]
IMO this synset raises another, more fundamental question which need to be discussed.

> mit sich selbst reden, laut nachdenken, Selbstgespräche führen, Monolog führen, philosophieren,  nachdenken

IMO these expressions have related meanings, but they are not synonyms, which can be substituted for each other in a given context. This is quite often the case. The cause is that Openthesaurus.de is not a wordnet, it's different. What does that mean for us?

**Comment by hdaSprachtechnologie** [comment]
solved
