### ISSUE TITLE
Small bug in hyponyms code:

### ISSUE THREAD

**Issue by JanEnglerIW** [hdaSprachtechnologie/odenet#43]
Hello, there is a small bug when using hyperonyms.

File [odenet_class.py:163](https://github.com/hdaSprachtechnologie/odenet/blob/master/odenet/odenet_class.py), in hypernyms_word(word)
    161 hyp_list = []
    162 for sense in senses:
--> 163     (ili,definition,de_definition, relations, words,ili_list) = check_synset(sense[1])
    164     for relation in relations:
    165         if relation[0] == "hypernym":

ValueError: too many values to unpack (expected 6)

Line 163 should be:
(ili,en_definition,de_definition, relations, words, ili_synsets,de_example) = check_synset(sense[1])

Regards
Jan

**Comment by hdaSprachtechnologie** [comment]
Thank you very much!
I solved it now.

Best,
Melanie
