### ISSUE TITLE
3201 nouns in deWordNet that are lowercase only 

### ISSUE THREAD

**Issue by AlexCherrypi** [hdaSprachtechnologie/odenet#44]
While looking at this fabolous german wordnet I found 3201 nouns (`partOfSpeech="n"`) that do not have any uppercase characters in them.)
That does not seem right...

[lowercaseNouns.json.zip](https://github.com/hdaSprachtechnologie/odenet/files/11584715/lowercaseNouns.json.zip)

Below is an excerpt of my list of all the words I found having a tag of `partOfSpeech="n"` but only lower case characters:

`
[
  "platzenlassen",
  "miteinander vertaktet",
  "gut durchdacht",
  "eingerahmt",
  "ungeheuer viele",
  "zwanghaft kontrollsüchtig",
  "(irgendwie) verfahren",
  "diebstahlsicher",
  "fast alle",
  "sich in allem einig sein",
  "einglasen",
  "erbärmliche",
  "zelebrieren",
  "sollte es erneut zu kommen",
  "sternhagelvoll",
  "nicht aktiv werden",
  "reinschlittern",
  "pustulös",
  "beschämende",
  "gestern",
  "kann man doch nicht machen",
  "ungeahndet",
  "okzipital",
  "wollen, dass endlich etwas passiert",
  "verstandgesteuert",
  "nächtelang",
  "geduldeterweise",
  "behördlich genehmigen",
  "problemnah",
  "irre viele",
  "sich umstellen",
  "vaginal",
  "mach's nicht so spannend",
  "zerlesen",
  "abgabenfrei",
  "zerfurcht",
  "eineinhalb",
  "benachteiligt",
  "ernten",
  "siehe unten",
  "rochieren",
  "junior",
  "bisschen dalli",
  "peroral",
  "magere",
  "...fleischproduktion",
  "nach vorn gerichtet",
  "unerledigt",
  "sich einklemmen",
  "bei bleiben",
  "stud.",
  "es ist noch nicht allzu lange her, dass",
  "es geht wieder aufwärts",
  "über das",
  "locker sitzen",
  "unglücklicherweise",
  "auf jemanden niederprasseln",
  "sauer",
  "aufeinander bezüglich",
  "intensiv beworben",
  "wegdrücken",
  "presto",
  "ähnlich klingend",
  "übel nehmen",
  "legt sich",
  "was auch immer",
  "aufmunitionieren",
  "sich bedienen",
  "tänzeln",
  "davonschwimmen",
  "paroxysmal",
  "ad hominem",
  "systemimmanent",
  "ungesühnt",
  "flussabwärts",
  "wie hieß noch gleich",
  "das mit",
  "nichts von all dem",
  "(jemanden irgendwo) erreichen",
  "totgeschwiegen",
  "erholungsbedürftig",
  "wetterbedingt",
  "momentweise",
  "fassförmig",
  "jemandem abringen",
  "verweben",
  "auserküren",
  "pitschnass",
  "angesprochen",
  "bereisen",
  "bis zuletzt",
  "zuerst einmal",
  "orange",
  "degressiv",
  "reprimieren",
  "sich anmaßen",
  "scheibenförmig",
  "audiovisuell",
  "warum bist du gekommen",
  "personenbezogen",
  "wenn es kommt, dann aber richtig",
  "wachstumsanregend",
  "wie geschaffen für",
  "postmortal",
  "verauktionieren",
  "selbst...",
  "nicht weggehen",
  "eins und eins zusammenzählen",
  "tabuisiert",
  "nicht abschalten",
  "nicht eine",
  "was ist los mit dir",
  "schon",
  "kaum noch zu bändigen",
  "vorschicken",
  "unbar",
  "gut wegkommen",
  "altertümelnd",
  "signum citationis",
  "unbehaust",
  "genderfair",
  "auskramen",
  "auch gelten für",
  "voranstellen",
  "anschwemmen",
  "so nicht gedacht",
  "zusammengepfuscht",
  "gestrichelt",
  "hellbraun",
  "3,141592653589793238",
  "hoch gelobt",
  "wir kümmern uns drum",
  "mäandern",
  "ad ultimo",
  "perioral",
  "leporellogefaltet",
  "ermahnend",
  "nicht gepfropft",
  "vereindeutigen",
  "zurechtgebastelt",
  "klarkommen müssen",
  "narrensicher",
  "streng päpstlich gesinnt",
  "vielgeliebt",
  "erwischt",
  "ausgekotzt",
  "glücklich davonkommen",
  "gruschen",
  "(na) das hast du ja toll hingekriegt",
  "sich rumärgern",
  "orangen",
  "promoviert",
  "etwas deichseln",
  "null zu null",
  "breit aufgestellt",
  "sühnen",
  "überbezahlt",
  "darauf gebe ich",
  "weiterleiten",
  "fehlerträchtig",
  "abertausend",
  "verteuern",
  "(voll) abfahren",
  "etwas bildlich vor sich sehen",
  "durchtränken",
  "postum",
  "frankieren",
  "vergleichbar mit",
  "bombardieren mit",
  "betriebseigen",
  "bis tief in",
  "muskelbepackt",
  "beige",
  "furchtbar, dies sagen zu müssen",
  "wiederfordern",
  "absengen",
  "veräppelt",
  "tief schlafen",
  "(er) gehört mir",
  "nicht veredelt",
  "televisionieren",
  "bestürmen ",
  "etwas wurde angesprochen",
  "zu unterst",
  "verunreinigen",
  "plastizieren",
  "...drama",
  "jemandem nichts zuleide tun",
  "ist gleich",
  "risikoscheu",
  "stirnrunzelnd",
  "hackedicht",
  "mit das",
  "beschatten",
  "jahrzehntelang",
  "ausschwärmen",
  "das war's dann wohl für",
  "akephal",
  "machtbesessen",
  "von morgens bis abends",
  "nicht wissen, wo man ist",
  "wär das okay für dich",
  "froh sein, dass etwas vorbei ist",
  "so lange fressen, bis es jemandem oben und unten wieder herauskommt",
  "sich zurückbildend",
  "vorne mit dabei",
  "(da ist) etwas zu verteilen",
  "darauf steht die ...strafe",
  "(durch) dick und dünn",
  "selbsternannt",
  "sich schwer verkaufen lassen",
  "sponsern",
  "homöotherm",
  "demoralisiert",
  "technophil",
  "gesattelt und gespornt",
  "(auf)keimen",
  "büschelweise",
  "viel gepriesen",
  "etwas ist nie genug",
  "wintergrün",
  "besitzt",
  "first class",
  "antiproliferativ",
  "infrarot",
  "einschrauben",
  "zurechtge...",
  "umfließen",
  "freimachen",
  "habilitatus",
  "ternär",
  "sich unterstehen",
  "vorschieben",
  "zeitlich nicht festgelegt",
  "hinkauern",
  "pansexuell",
  "rostfrei",
  "ganz allgemein",
  "an nichts sparen",
  "unerfreulicherweise",
  "geht es",
  "denk nach bevor du sprichst",
  "ärgerlicherweise",
  "hart",
  "sich stark vermehren",
  "konformationell",
  "durchfechten",
  "namensgleich",
  "jemanden reinlegen",
  "hinge...",
  "funktioniert nur",
  "millionenfach",
  "verkorkst",
  "übers",
  "depilieren",
  "kurz nach",
  "blind werden",
  "singbegeistert",
  "heißgeliebt",
  "kaum jemand",
  "gemildert",
  "kurz davor  aufzuhören",
  "pladdernass",
  "herleiern",
  "antitumorös",
  "vieltausendmal",
  "veredelt",
  "definitiv wissen",
  "am wohlgesittetsten",
  "und so weiter ad infinitum",
  "fliederfarbig",
  "(darum) können wir uns ein andermal kümmern",
  "reintun",
  "es kommt dick",
  "umzäunt",
  "noch einmal vollmachen",
  "etwas zu lesen",
  "jedenfalls danke",
  "nicht genug zu essen bekommen",
  "straffrei",
  "mondsüchtig",
  "ausgezeichnet",
  "rostral",
  "tot umfallen",
  "(sinnlos) verballern",
  "maschinengeschrieben",
  "beurlauben",
  "sich ziehen",
  "duobus litigantibus tertius gaudet",
  "nicht mehr zu halten",
  "nicht benutzt werden",
  "zu stark bevölkert",
  "damit wir uns richtig verstehen:",
  "wenn es machbar ist",
  "jemandem eins überbraten",
  "'n guten",
  "um sich schmeißen",
  "ordnungslos",
  "vergoren",
  "beidseits",
  "gut zu erreichen",
  "vergattern",
  "bernsteinfarben",
  "extrem wenig",
  "(etwas für sich) herausschlagen",
  "wenn schon, denn schon",
  "sich eingraben",
  "unzählige",
  "phototrop",
  "abschabend",
  "furchig",
  "wieder aufbereiten",
  "eingreifend",
  "intrapleural",
  "alles oder nichts",
  "bis letztens",
  "kein einziger",
  "sich etwas vor halten",
  "ecru",
  "brüderlich teilen",
  "wiedererlangen",
  "herumkugeln",
  "fressgierig",
  "plastifizieren",
  "hineinlesen",
  "wegdösen",
  "was willst du",
  "wiederbewalden",
  "genoppt",
  "hochladen",
  "kläglich aussehen",
  "sich erbittert wehren",
  "etwas herausbekommen",
  "intraneural",
  "prima facie",
  "nicht so gedacht",
  "entzaubert",
  "verstauben",
  "metromorph",
  "thoracal",
  "mittenmang",
  "aushauchen",
  "(völlig) verwüstet",
  "nicht beheizt",
  "so war es",
  "mehrsprachig",
  "kardiovertieren",
  "sich nicht verlassen mögen",
  "shopping trolley",
  "zusammenstecken",
...
]
`

**Comment by hdaSprachtechnologie** [comment]
This is true and truly wrong. Do you have an idea on how to correct them automatically? Some of them are pos "a" (such as "technophil"), some of them are pos "v" (such as "plastifizieren") and many are multi-word lexemes (such as "zu stark bevölkert"). If we'd have a list of the words and their correct pos, then it'd be easy. But how to get to this list?

**Comment by hdaSprachtechnologie** [comment]
I have now extracted all synset-IDs for these words, added POSs by spacy and put them in different lists:
- mwe.txt contains multi-word expressions
- [mwe.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653483/mwe.txt)
- adjadv.txt contains adjectives and adverbs (concerning to spacy)
- [adjadv.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653491/adjadv.txt)
- nouns.txt contains nouns
- [nouns.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653510/nouns.txt)
- verbs.txt contains verbs
- [verbs.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653494/verbs.txt)
- names.txt contains classifications as "NE" by spacy, mostly unknown, I'd say
[names.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653486/names.txt)
- others.txt contains other categories
[others.txt](https://github.com/hdaSprachtechnologie/odenet/files/11653512/others.txt)

**Comment by hdaSprachtechnologie** [comment]
I have now corrected all the ones that are not multi-word lexemes. For these, we need a different solution.

**Comment by hdaSprachtechnologie** [comment]
I have now worked on all these words. Thank you for pointing them out!
