### ISSUE TITLE
Pathing breaks on different computer

### ISSUE THREAD

**Issue by bionicles** [hdaSprachtechnologie/odenet#8]
This line:
```
de_wn = open(r"C:\Users\melaniesiegel\Documents\05_Projekte\WordNet\OdeNet\deWNaccess\odenet_oneline.xml","r",encoding="utf-8")
```
only works on your computer

try `os.path.join(os.path.dirname(__file__), f"{FILENAME}.xml")` -- then it's gonna also work on linux computers like mine, and other windows computers with different names/folders

**Comment by hdaSprachtechnologie** [comment]
true, thank you!
I changed this.
